#! /usr/bin/env python
"""
Sample script that displays the ATR of inserted cards.

__author__ = "http://www.gemalto.com"

Copyright 2001-2010 gemalto
Author: Jean-Daniel Aussel, mailto:jean-daniel.aussel@gemalto.com
Copyright 2010 Ludovic Rousseau
Author: Ludovic Rousseau, mailto:ludovic.rousseau@free.fr

This file is part of pyscard.

pyscard is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation; either version 2.1 of the License, or
(at your option) any later version.

pyscard is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with pyscard; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
"""
from smartcard.Exceptions import NoCardException
from smartcard.Exceptions import CardConnectionException
from smartcard.System import readers
from smartcard.util import toHexString

def Replace(String):
    String = String.replace(" ","")
    return String

for reader in readers():
    try:
        connection = reader.createConnection()
        connection.connect()
        ATRaux = toHexString(connection.getATR())
        ATR = Replace(ATRaux)
        if ATR == "3B6F0000806645460138180353023124829000":
            print("ATR:CORRECTO")
        elif ATR == "3B6800008066A20308013107":
            print("ATR:CORRECTO")
        elif ATR == "3B6F0000806645460138180353023110829000":
            print("ATR:CORRECTO")
        elif ATR == "3B6F00008066B0070101770753023110829000":
            print("ATR:CORRECTO")
        else:
            print("ATR:INCORRECTO")
    except NoCardException:
        print ("ATR:SIN_TARJETA")
    except CardConnectionException:
        print ("ATR:SIN_TARJETA")

import sys
if 'win32' == sys.platform:
    print("press Enter to continue")
    sys.stdin.read(1)

