#!/bin/bash
# Demonio para el funcionamiento de Salamandra.
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
export DISPLAY=:0.0


i=0

while true
do
	sleep 5
	# Controlamos si esta introducida la tarjeta.
	estadoTarjeta=`/usr/bin/python3 /etc/bus/apps/salamandra/SalamandraTIUSv0.25/getATR3`
	echo $estadoTarjeta

	if [ $estadoTarjeta = "ATR:CORRECTO" ];then
		echo "TARJETA CORRECTA\n" 
		if [ $i -eq 1 ];then
			xinput set-prop 8 'Device Enabled' 1
			xinput set-prop 9 'Device Enabled' 1
			xinput set-prop 10 'Device Enabled' 1
			xinput set-prop 11 'Device Enabled' 1

			pkill feh 
			# Desbloqueamos el teclado.
			/home/bibliotecario/avisoencendidosalamandra.sh
			
				
		fi
		i=0

	else
		if [ $i -eq 0 ];then
			echo "TARJETA INCORRECTA" 
			# Cierra la ventana con la imagen, por si estuviese abierta.
			kill -9 `ps -ef | grep imagen | awk '{print $2}'`
			pkill feh
			sleep 1
			# Mostramos la ventana con la imagen del salamandra.
			#/usr/bin/python3 /etc/bus/apps/salamandra/SalamandraTIUSv0.25/imagen.py &
			# Bloqueamos el teclado y el ratón.
			xinput set-prop 8 'Device Enabled' 0
			xinput set-prop 9 'Device Enabled' 0
			xinput set-prop 10 'Device Enabled' 0
			xinput set-prop 11 'Device Enabled' 0
			/home/bibliotecario/avisoencendidosalamandraFondo.sh &
			sleep 1
			# Matamos el proceso del firefox.
			#kill -9 `ps -ef | grep firefox | awk '{print $2}'`
			#kill -9 `ps -ef | grep chrome | awk '{print $2}'`
			pkill firefox
			pkill chrome
			pkill soffice*
			pkill libreoffice*
			# Establecemos que ya se ha detectado que no hay tarjeta, para mostrar solo una vez la ventana.
			i=1
			pkill xfce4-popup-whiskermenu

		else
			echo "TARJETA INCORRECTA"
			#kill -9 `ps -ef | grep firefox | awk '{print $2}'`
			#kill -9 `ps -ef | grep chrome | awk '{print $2}'`
			pkill firefox
			pkill chrome
			pkill soffice*
			pkill libreoffice*
			# Bloqueamos el teclado y raton.
			xinput set-prop 8 'Device Enabled' 0
			xinput set-prop 9 'Device Enabled' 0
			xinput set-prop 10 'Device Enabled' 0
			xinput set-prop 11 'Device Enabled' 0
			pkill xfce4-popup-whiskermenu
		fi

		
	fi

done	




